export const servicesData = {
        "serviceCategories": [
            {
                "id": "office-olympics",
                "name": "Office Olympics",
                "description": "Fun competitive office games",
                "icon": "🏆",
                "gradient": "bg-gradient-to-br from-[#00FFAB] via-green-400 to-green-500",
                "bubbleColor": "bg-gray-800",
                "textColor": "text-black",
                "subtitleColor": "text-gray-800",
                "experienceColor": "text-gray-700"
            },
            {
                "id": "wellness",
                "name": "Wellness Programs",
                "description": "Health & wellbeing focus",
                "icon": "🧘",
                "gradient": "bg-gradient-to-br from-gray-700 via-gray-800 to-black",
                "bubbleColor": "bg-[#00FFAB]",
                "textColor": "text-white",
                "subtitleColor": "text-gray-200",
                "experienceColor": "text-gray-300"
            },
            {
                "id": "ice-breakers",
                "name": "Ice Breakers",
                "description": "Break the ice and connect",
                "icon": "🧊",
                "gradient": "bg-gradient-to-br from-[#00FFAB] via-green-400 to-green-500",
                "bubbleColor": "bg-gray-800",
                "textColor": "text-black",
                "subtitleColor": "text-gray-800",
                "experienceColor": "text-gray-700"
            },
            {
                "id": "team-building",
                "name": "Team Building",
                "description": "Build stronger connections",
                "icon": "🎯",
                "gradient": "bg-gradient-to-br from-gray-700 via-gray-800 to-black",
                "bubbleColor": "bg-[#00FFAB]",
                "textColor": "text-white",
                "subtitleColor": "text-gray-200",
                "experienceColor": "text-gray-300"
            },
            {
                "id": "creative-workshop",
                "name": "Creative Workshops",
                "description": "Unleash your creativity",
                "icon": "🎨",
                "gradient": "bg-gradient-to-br from-[#00FFAB] via-green-400 to-green-500",
                "bubbleColor": "bg-gray-800",
                "textColor": "text-black",
                "subtitleColor": "text-gray-800",
                "experienceColor": "text-gray-700"
            },
            {
                "id": "sports",
                "name": "Sports Events",
                "description": "Competitive team activities",
                "icon": "⚽",
                "gradient": "bg-gradient-to-br from-gray-700 via-gray-800 to-black",
                "bubbleColor": "bg-[#00FFAB]",
                "textColor": "text-white",
                "subtitleColor": "text-gray-200",
                "experienceColor": "text-gray-300"
            },
            {
                "id": "entertainment",
                "name": "Festive Celebrations",
                "description": "Fun & engaging experiences",
                "icon": "🎭",
                "gradient": "bg-gradient-to-br from-[#00FFAB] via-green-400 to-green-500",
                "bubbleColor": "bg-gray-800",
                "textColor": "text-black",
                "subtitleColor": "text-gray-800",
                "experienceColor": "text-gray-700"
            }
        ],
        "services": [
            {
                "id": "chain-reaction",
                "title": "Chain Reaction",
                "subtitle": "Your link to victory! Clip fast, but clip carefully.",
                "category": "office-olympics",
                "description": "Connect as many paperclips as possible before time runs out. The longest chain wins. Will your team create a never-ending chain, or will it fall apart under pressure?",
                "duration": "20 minutes",
                "participants": "5-10",
                "difficulty": "Easy",
                "location": "Outdoor/Indoor",
                "skills": ["Time Management", "Problem Solving", "Collaboration", "Efficiency"],
                "pricing": "Group Pricing",
                "includes": ["Paperclips", "Timer", "Measuring Tools", "Team Scoreboard"],
                "requirements": ["Tables", "Chairs", "Good Lighting", "Open Space"]
            },
            {
                "id": "chair-force-one",
                "title": "Chair Force One",
                "subtitle": "The Office Grand Prix!",
                "category": "office-olympics",
                "description": "Who needs a racetrack when you have a smooth office floor and rolling chairs? Zip across to the finish line to clinch the gold. Ready, set, race!",
                "duration": "30 minutes",
                "participants": "4-6",
                "difficulty": "Hard",
                "location": "Indoor",
                "skills": ["Focus", "Speed", "Performance", "Accuracy"],
                "pricing": "Group Pricing",
                "includes": ["Rolling Chairs", "Safety Equipment", "Race Track Setup", "Timer"],
                "requirements": ["Smooth Floor", "Safety Padding", "Clear Pathway", "First Aid Kit"]
            },
            {
                "id": "fastest-finger-first",
                "title": "Fastest Finger First",
                "subtitle": "Can you type faster than the speed of thought?",
                "category": "office-olympics",
                "description": "Compete in a race against time to see who can hit the highest words-per-minute without breaking a sweat! Beware of the dreaded typos—they might cost you the gold!",
                "duration": "30 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Focus", "Speed", "Performance", "Accuracy"],
                "pricing": "Per Person",
                "includes": ["Computers/Laptops", "Typing Software", "Timer", "Scoreboard"],
                "requirements": ["Workstations", "Stable Internet", "Keyboards", "Screens"]
            },
            {
                "id": "stationery-sprint",
                "title": "Stationary Sprint",
                "subtitle": "Slow and steady wins the race!",
                "category": "office-olympics",
                "description": "Dash across the room while juggling office supplies. Drop it, and you start over. Test your coordination and speed in this game of steady hands and quick feet.",
                "duration": "20 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Outdoor/Indoor",
                "skills": ["Balance", "Concentration", "Stability", "Agility"],
                "pricing": "Per Person",
                "includes": ["Office Supplies", "Obstacle Course", "Timer", "Safety Equipment"],
                "requirements": ["Open Space", "Various Office Items", "Clear Pathway", "Safety Mats"]
            },
            {
                "id": "sticky-situation",
                "title": "Sticky Situation",
                "subtitle": "Get stuck on this challenge!",
                "category": "office-olympics",
                "description": "Get as many notes on your teammate as possible. Will you place them neatly, or just go for pure quantity? Either way, may the stickiest team win!",
                "duration": "20 minutes",
                "participants": "Pairs",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Communication", "Memory Recall", "Observation", "Awareness"],
                "pricing": "Group Pricing",
                "includes": ["Sticky Notes", "Timer", "Counting Tools", "Team Scoreboard"],
                "requirements": ["Indoor Space", "Tables", "Good Lighting", "Sticky Notes Supply"]
            },
            {
                "id": "flight-club",
                "title": "The Flight Club",
                "subtitle": "Who needs an airport? Get ready for takeoff!",
                "category": "office-olympics",
                "description": "Send your handmade aircraft soaring through the air. Whether you go for sleek aerodynamics or wild creativity, only the best design will rule the air! Will it be a smooth flight or a crash landing?",
                "duration": "30 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Creativity", "Design Testing", "Innovation", "Adaptability"],
                "pricing": "Per Person",
                "includes": ["Paper", "Craft Materials", "Measuring Tools", "Launch Area"],
                "requirements": ["Large Space", "Craft Supplies", "Tables", "Measuring Equipment"]
            },
            {
                "id": "straw-lympics",
                "title": "The Straw-lympics",
                "subtitle": "Throw Far, Throw Smart!",
                "category": "office-olympics",
                "description": "This isn't just about brute force - take aim, grip your straw, and launch it across the room with precision. Can you break the distance record or will it nosedive before takeoff?",
                "duration": "30 minutes",
                "participants": "Individual",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Control", "Initiative", "Precision", "Accuracy"],
                "pricing": "Per Person",
                "includes": ["Straws", "Measuring Tools", "Launch Area", "Scoreboard"],
                "requirements": ["Open Space", "Measuring Tape", "Safety Area", "Target Markers"]
            },
            {
                "id": "tug-life",
                "title": "The Tug Life",
                "subtitle": "Pull, Slide, and Conquer!",
                "category": "office-olympics",
                "description": "Grab the rope, plant your feet, and let the tugging begin. Victory lies in teamwork and synergy. Will you be pulled away, or will you pull through?",
                "duration": "30 minutes",
                "participants": "5-10",
                "difficulty": "Hard",
                "location": "Indoor",
                "skills": ["Strategy", "Resilience", "Teamwork", "Alignment"],
                "pricing": "Group Pricing",
                "includes": ["Rope", "Safety Equipment", "Ground Markings", "First Aid Kit"],
                "requirements": ["Open Space", "Non-slip Surface", "Safety Gear", "Medical Support"]
            },
            {
                "id": "chair-desk-yoga",
                "title": "Chair-Desk Yoga",
                "subtitle": "A stress-relieving session without leaving your seat",
                "category": "wellness",
                "description": "Designed for office settings, this practice uses basic stretches and breathing techniques to open up stiff muscles and realign posture. No need to roll out a mat; relief is one seat away.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Flexibility", "Posture", "Release", "Clarity"],
                "pricing": "Per Person",
                "includes": ["Certified Instructor", "Guided Session", "Breathing Techniques", "Posture Tips"],
                "requirements": ["Office Chairs", "Quiet Space", "Comfortable Clothing", "Water"]
            },
            {
                "id": "mat-yoga",
                "title": "Mat Yoga",
                "subtitle": "A slow and soulful flow",
                "category": "wellness",
                "description": "This session blends breath, movement, and mindfulness to help employees disconnect from digital noise and reconnect with themselves.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Balance", "Flexibility", "Strength", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Yoga Mats", "Certified Instructor", "Props", "Relaxation Music"],
                "requirements": ["Yoga Studio/Space", "Mats", "Comfortable Clothing", "Water Bottles"]
            },
            {
                "id": "stress-management",
                "title": "Stress Management",
                "subtitle": "Explore physical and mental tools to decode stress",
                "category": "wellness",
                "description": "Participants explore physical and mental tools to decode stress and shift their responses. Through movement, breathwork, and brief self-inquiry, they'll learn simple rituals to carry into daily life.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Icebreaking", "Initiative", "Observation", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Stress Assessment Tools", "Breathing Techniques", "Movement Exercises", "Take-home Guide"],
                "requirements": ["Quiet Space", "Comfortable Seating", "Notebook", "Water"]
            },
            {
                "id": "dance-fitness",
                "title": "Dance Fitness",
                "subtitle": "A mood-boosting workout disguised as a party",
                "category": "wellness",
                "description": "This high-energy dance session blends simple choreography with contagious music to get everyone moving, sweating, and smiling. No dance background? No problem. Just let go and rediscover joy through movement.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Icebreaking", "Initiative", "Observation", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Dance Instructor", "Music System", "Choreography", "Water Breaks"],
                "requirements": ["Dance Studio/Space", "Sound System", "Comfortable Clothing", "Water"]
            },
            {
                "id": "zumba",
                "title": "Zumba",
                "subtitle": "A global favorite for a reason",
                "category": "wellness",
                "description": "Zumba infuses Latin beats with full-body cardio for a session that's equally fun and effective. It's less about perfect steps and more about good vibes and moving freely.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Icebreaking", "Initiative", "Observation", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Certified Zumba Instructor", "Music System", "Latin Beats", "Energy Boosters"],
                "requirements": ["Dance Floor", "Sound System", "Comfortable Clothing", "Water Bottles"]
            },
            {
                "id": "laughter-yoga",
                "title": "Laughter Yoga",
                "subtitle": "Gentle movement, breathing, and uncontrollable laughter",
                "category": "wellness",
                "description": "This light-hearted session blends gentle movement, breathing techniques, and uncontrollable laughter. As awkwardness fades, joy takes center stage. Ideal for energizing large teams.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Icebreaking", "Initiative", "Observation", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Laughter Yoga Instructor", "Breathing Exercises", "Laughter Techniques", "Mood Boosters"],
                "requirements": ["Open Space", "Comfortable Seating", "Relaxed Atmosphere", "Water"]
            },
            {
                "id": "face-yoga",
                "title": "Face Yoga",
                "subtitle": "Targets stress and fatigue in facial muscles",
                "category": "wellness",
                "description": "A refreshing practice that targets stress, fatigue, and tightness in facial muscles, especially for screen-heavy roles. Through guided techniques and micro-movements, this session awakens facial awareness.",
                "duration": "60 minutes",
                "participants": "Individual",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Icebreaking", "Initiative", "Observation", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Face Yoga Instructor", "Facial Techniques", "Relaxation Methods", "Eye Exercises"],
                "requirements": ["Mirrors", "Comfortable Seating", "Good Lighting", "Water"]
            },
            {
                "id": "human-bingo",
                "title": "Human Bingo",
                "subtitle": "A quirky twist on bingo with real-life traits",
                "category": "ice-breakers",
                "description": "Instead of numbers, you're chasing real-life traits and oddball facts about coworkers. Laughter is inevitable as unexpected connections unfold. Perfect for sparking curiosity and breaking personal bubbles.",
                "duration": "30 minutes",
                "participants": "Individual",
                "difficulty": "Hard",
                "location": "Indoor",
                "skills": ["Icebreaking", "Initiative", "Observation", "Awareness"],
                "pricing": "Per Person",
                "includes": ["Custom Bingo Cards", "Markers", "Prize System", "Facilitation"],
                "requirements": ["Bingo Cards", "Writing Materials", "Open Space", "Prize Collection"]
            },
            {
                "id": "speed-networking",
                "title": "Speed Networking",
                "subtitle": "Not your usual roundtable",
                "category": "ice-breakers",
                "description": "A time-based rotation that keeps the energy flowing. Participants get just enough time to break the surface before moving on. It's fast, light, and leaves people wanting to reconnect deeper later.",
                "duration": "30 minutes",
                "participants": "Individual",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Communication", "Confidence", "Exposure", "Active Listening"],
                "pricing": "Per Person",
                "includes": ["Timer System", "Name Tags", "Conversation Starters", "Networking Cards"],
                "requirements": ["Tables/Chairs", "Timer", "Name Tags", "Open Layout"]
            },
            {
                "id": "one-word-story",
                "title": "One Word Story",
                "subtitle": "Each person adds one word to build a story",
                "category": "ice-breakers",
                "description": "Each person adds one word at a time to build a hilarious and creative team story. It's a collective mind game of timing, teamwork, and tongue-tied turns. Chaos meets creativity.",
                "duration": "20 minutes",
                "participants": "Individual",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Quick Thinking", "Spontaneity", "Teamwork", "Creativity"],
                "pricing": "Group Pricing",
                "includes": ["Facilitation", "Story Recording", "Creative Prompts", "Laughter"],
                "requirements": ["Circle Seating", "Recorder", "Comfortable Space", "Timer"]
            },
            {
                "id": "quiet-queue",
                "title": "The Quiet Queue",
                "subtitle": "Line up by criteria without talking",
                "category": "ice-breakers",
                "description": "The entire team must line up by criteria in order but there's a catch - No talking allowed. Gestures become language, laughter becomes common, and assumptions are tested.",
                "duration": "20 minutes",
                "participants": "10-20",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Awareness", "Collaboration", "Strategy", "Alignment"],
                "pricing": "Group Pricing",
                "includes": ["Criteria Cards", "Facilitation", "Non-verbal Communication Guide", "Timer"],
                "requirements": ["Open Space", "Clear Area", "Facilitator", "Various Criteria"]
            },
            {
                "id": "storytelling-circle",
                "title": "Storytelling Circle",
                "subtitle": "One spark sets the tale in motion",
                "category": "ice-breakers",
                "description": "Each participant adds their twist, layering humor, drama, or mystery into a story that builds line by line. Expect sudden plot turns and unexpected finales. It's spontaneous, inclusive, and surprisingly revealing.",
                "duration": "20 minutes",
                "participants": "5-10",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Creativity", "Imagination", "Spontaneity", "Adaptability"],
                "pricing": "Group Pricing",
                "includes": ["Story Prompts", "Recording", "Creative Facilitation", "Circle Setup"],
                "requirements": ["Circle Seating", "Comfortable Space", "Story Starters", "Timer"]
            },
            {
                "id": "chopstick-relay",
                "title": "Chopstick Relay",
                "subtitle": "Pass tiny objects using only chopsticks",
                "category": "ice-breakers",
                "description": "A fast-paced race where participants must pass tiny objects using only chopsticks without dropping the momentum. Coordination, composure, and calm nerves are key. The simplicity belies its hilarious difficulty.",
                "duration": "45 minutes",
                "participants": "10-20",
                "difficulty": "Hard",
                "location": "Outdoor",
                "skills": ["Dexterity", "Focus", "Teamwork", "Balance"],
                "pricing": "Group Pricing",
                "includes": ["Chopsticks", "Small Objects", "Timer", "Relay Setup"],
                "requirements": ["Tables", "Chopsticks", "Small Items", "Clear Space"]
            },
            {
                "id": "number-game",
                "title": "The Number Game",
                "subtitle": "Precision is everything, panic is the enemy",
                "category": "ice-breakers",
                "description": "Teams must respond lightning-fast to number calls by visually forming or holding up that number as a group. It's a test of cohesion, quick alignment, and agility.",
                "duration": "20 minutes",
                "participants": "5-10",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Coordination", "Reflexes", "Unity", "Agility"],
                "pricing": "Group Pricing",
                "includes": ["Number Cards", "Timer", "Facilitation", "Scoring System"],
                "requirements": ["Open Space", "Number Cards", "Clear Visibility", "Timer"]
            },
            {
                "id": "sheep-shepherd",
                "title": "Sheep & Shepherd",
                "subtitle": "Move through challenges without seeing or speaking",
                "category": "team-building",
                "description": "Teams must move through a challenge without seeing or speaking, guided only by the leader's whistle commands. As instincts kick in, participants must sharpen their senses and listen closely.",
                "duration": "60 minutes",
                "participants": "10-20",
                "difficulty": "Medium",
                "location": "Outdoor/Indoor",
                "skills": ["Direction", "Leadership", "Responsiveness", "Communication"],
                "pricing": "Group Pricing",
                "includes": ["Whistle", "Blindfolds", "Obstacle Course", "Safety Equipment"],
                "requirements": ["Safe Area", "Whistle", "Blindfolds", "Clear Commands"]
            },
            {
                "id": "trivia",
                "title": "Trivia",
                "subtitle": "Think you know it all?",
                "category": "team-building",
                "description": "This lively game pits teams against each other in a battle of wits, strategy, and speed. With questions spanning unexpected topics, it encourages collaboration, lateral thinking, and even a few wild guesses.",
                "duration": "45 minutes",
                "participants": "4-8",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Decision Making", "Recall", "Strategy", "Coordination"],
                "pricing": "Group Pricing",
                "includes": ["Question Bank", "Scoring System", "Buzzers", "Prizes"],
                "requirements": ["Trivia Questions", "Scoring Materials", "Seating", "Timer"]
            },
            {
                "id": "human-knot",
                "title": "Human Knot",
                "subtitle": "Tied up in a knot they must unravel",
                "category": "team-building",
                "description": "A physical metaphor for workplace challenges; teams are literally tied up in a knot they must unravel without letting go. It's awkward, funny, and surprisingly deep, as people realize collective thinking is the only way out.",
                "duration": "45 minutes",
                "participants": "8-10",
                "difficulty": "Medium",
                "location": "Outdoor/Indoor",
                "skills": ["Awareness", "Cohesion", "Problem Solving", "Alignment"],
                "pricing": "Group Pricing",
                "includes": ["Facilitation", "Safety Guidelines", "Problem Solving Guide", "Debrief"],
                "requirements": ["Open Space", "Safety Area", "Comfortable Clothing", "Facilitator"]
            },
            {
                "id": "treasure-hunt",
                "title": "Treasure Hunt",
                "subtitle": "Turn your office into a map of clues",
                "category": "team-building",
                "description": "Teams race against time, decoding clues that send them exploring hidden corners and overlooked spots across the office. Expect light cardio, lots of laughs, and surprising aha moments.",
                "duration": "45 minutes",
                "participants": "5-10",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Collaboration", "Observation", "Strategy", "Agility"],
                "pricing": "Group Pricing",
                "includes": ["Clue Cards", "Treasure Map", "Prizes", "Timer"],
                "requirements": ["Office Space", "Clues", "Hiding Spots", "Prizes"]
            },
            {
                "id": "scavenger-hunt",
                "title": "Scavenger Hunt",
                "subtitle": "Locate, identify, and creatively present items",
                "category": "team-building",
                "description": "Fast-paced and highly interactive, this hunt pushes teams to locate, identify, and creatively present everyday office items in new ways. Some clues might require quick thinking, while others need humor and persuasion.",
                "duration": "60 minutes",
                "participants": "10-15",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Initiative", "Observation", "Quick Thinking", "Awareness"],
                "pricing": "Group Pricing",
                "includes": ["Item List", "Clue Cards", "Collection Bags", "Timer"],
                "requirements": ["Various Items", "List", "Collection Materials", "Timer"]
            },
            {
                "id": "giant-dare-jenga",
                "title": "Giant Dare Jenga",
                "subtitle": "A high-stakes tower of tension",
                "category": "team-building",
                "description": "Every block you pull comes with a bold challenge. As the structure gets shakier, so does everyone's ability to keep a straight face. This game adds courage, spontaneity, and laughter to the classic format.",
                "duration": "60 minutes",
                "participants": "4-6",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Confidence", "Spontaneity", "Risk-Taking", "Initiative"],
                "pricing": "Group Pricing",
                "includes": ["Giant Jenga Set", "Dare Cards", "Timer", "Safety Mat"],
                "requirements": ["Jenga Set", "Dare Cards", "Flat Surface", "Safe Area"]
            },
            {
                "id": "blind-drawing",
                "title": "Blind Drawing",
                "subtitle": "One partner can see, one cannot",
                "category": "team-building",
                "description": "Together they must recreate an image using only verbal guidance and interpretation. Back-to-back and blindfolded, this deceptively simple task unearths communication gaps and listening skills in real time.",
                "duration": "60 minutes",
                "participants": "2",
                "difficulty": "Easy",
                "location": "Indoor",
                "skills": ["Coordination", "Creativity", "Interpretation", "Comprehension"],
                "pricing": "Group Pricing",
                "includes": ["Drawing Materials", "Image Cards", "Blindfolds", "Timer"],
                "requirements": ["Paper", "Pencils", "Images", "Blindfolds"]
            },
            {
                "id": "puzzle-hustle",
                "title": "Puzzle Hustle",
                "subtitle": "Some pieces are missing and held by rival teams",
                "category": "team-building",
                "description": "Teams work on seemingly simple puzzles until they realize some pieces are missing and held by rival teams. Now begins a game of negotiation, strategy, and alliance building. This brings out resourcefulness and deal-making skills.",
                "duration": "60 minutes",
                "participants": "4-8",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Flexibility", "Negotiation", "Strategy", "Diplomacy"],
                "pricing": "Group Pricing",
                "includes": ["Puzzle Sets", "Trading Cards", "Timer", "Negotiation Guide"],
                "requirements": ["Puzzle Sets", "Tables", "Timer", "Separate Areas"]
            },
            {
                "id": "shape-shifters",
                "title": "Shape Shifters",
                "subtitle": "Transform a loose rope into a perfect shape",
                "category": "team-building",
                "description": "Blindfolded and disoriented, participants must transform a loose rope into a perfect shape using only words. This silent chaos reveals the importance of structure, delegation, and clarity of instruction.",
                "duration": "45 minutes",
                "participants": "10-20",
                "difficulty": "Medium",
                "location": "Outdoor/Indoor",
                "skills": ["Correction", "Navigation", "Structure", "Calibration"],
                "pricing": "Group Pricing",
                "includes": ["Rope", "Blindfolds", "Shape Cards", "Timer"],
                "requirements": ["Rope", "Blindfolds", "Open Space", "Shape Templates"]
            },
            {
                "id": "frostbite",
                "title": "Frostbite",
                "subtitle": "Stranded in an imaginary snowstorm",
                "category": "team-building",
                "description": "Your team has one goal: build a functional shelter. But there's a twist! The leader can't touch anything, and the team can't see. Survival depends on leadership, adaptability, and translating vision into action.",
                "duration": "60 minutes",
                "participants": "10-20",
                "difficulty": "Hard",
                "location": "Indoor",
                "skills": ["Delegation", "Leadership", "Resilience", "Adaptability"],
                "pricing": "Group Pricing",
                "includes": ["Building Materials", "Blindfolds", "Timer", "Survival Guide"],
                "requirements": ["Building Materials", "Blindfolds", "Open Space", "Timer"]
            },
            {
                "id": "carpet-flip",
                "title": "Carpet Flip",
                "subtitle": "Flip the mat over without stepping off",
                "category": "team-building",
                "description": "Your team stands on a large mat with a single goal: flip it over without stepping off. Sounds easy, until the physical and strategic constraints kick in. It's all about body coordination and mutual support.",
                "duration": "45 minutes",
                "participants": "10-15",
                "difficulty": "Medium",
                "location": "Indoor",
                "skills": ["Execution", "Planning", "Support", "Coordination"],
                "pricing": "Group Pricing",
                "includes": ["Large Mat", "Timer", "Survival Guide"],
                "requirements": ["Building Materials", "Blindfolds", "Open Space", "Timer"]
            },
                {
                    "id": "tied-together",
                    "title": "Tied Together",
                    "subtitle": "Your team is literally tied together",
                    "category": "team-building",
                    "description": "Quite literally, your team is tied together. Every task now requires thoughtful motion, careful syncing, and an unspoken rhythm of cooperation. This high-energy, movement based challenge reveals how interconnected thinking leads to seamless execution.",
                    "duration": "45 minutes",
                    "participants": "10-20",
                    "difficulty": "Medium",
                    "location": "Outdoor/Indoor",
                    "skills": ["Dependability", "Harmony", "Synchronization", "Agility"],
                    "pricing": "Group Pricing",
                    "includes": ["Rope/Ties", "Timer", "Activity Guide", "Safety Equipment"],
                    "requirements": ["Open Space", "Rope/Ties", "Safety Area", "Timer"]
                },
                {
                    "id": "minefield",
                    "title": "Minefield",
                    "subtitle": "Navigate through invisible mines with precise verbal cues",
                    "category": "team-building",
                    "description": "A maze of invisible 'mines' lies ahead. One player is blindfolded; the rest must guide them out using only precise verbal cues. A test of clarity, trust, and shared mental models, this challenge puts team dynamics under a tight lens.",
                    "duration": "60 minutes",
                    "participants": "8-12",
                    "difficulty": "Hard",
                    "location": "Outdoor/Indoor",
                    "skills": ["Navigation", "Precision", "Trust", "Clarity"],
                    "pricing": "Group Pricing",
                    "includes": ["Blindfolds", "Mine Markers", "Timer", "Safety Equipment"],
                    "requirements": ["Open Space", "Blindfolds", "Markers", "Clear Commands"]
                },
                {
                    "id": "paper-tower-build",
                    "title": "Paper Tower Build",
                    "subtitle": "Build the tallest freestanding tower with paper and tape",
                    "category": "team-building",
                    "description": "With nothing but sheets of paper and tape, teams are challenged to build the tallest possible freestanding tower. What seems like child's play quickly becomes an exercise in structural design, group decision-making, and balancing speed with stability.",
                    "duration": "45 minutes",
                    "participants": "4-6",
                    "difficulty": "Medium",
                    "location": "Indoor",
                    "skills": ["Engineering", "Focus", "Optimization", "Coordination"],
                    "pricing": "Group Pricing",
                    "includes": ["Paper", "Tape", "Measuring Tools", "Timer"],
                    "requirements": ["Tables", "Paper", "Tape", "Measuring Equipment"]
                },
                {
                    "id": "balloon-furniture",
                    "title": "Balloon Furniture",
                    "subtitle": "Build actual usable furniture with balloons and tape",
                    "category": "team-building",
                    "description": "Teams are tasked with building actual, usable furniture out of balloons and tape. Every squeak and pop adds urgency, and creativity is tested against structural limits. A wildly fun but surprisingly effective exercise in innovation and hands-on problem solving.",
                    "duration": "60 minutes",
                    "participants": "5-10",
                    "difficulty": "Hard",
                    "location": "Indoor",
                    "skills": ["Execution", "Ingenuity", "Innovation", "Dexterity"],
                    "pricing": "Group Pricing",
                    "includes": ["Balloons", "Tape", "Pump", "Timer"],
                    "requirements": ["Open Space", "Balloons", "Tape", "Pump"]
                },
                {
                    "id": "clayground",
                    "title": "Clayground",
                    "subtitle": "Hands On, Stress Off!",
                    "category": "creative-workshop",
                    "description": "Who needs therapy when you can slap some clay around and call it art? Get your hands messy and your mind clear with a Hand Pottery session where stress melts like clay in your palm. Let's turn work pressure into clay masterpieces!",
                    "duration": "60 minutes",
                    "participants": "5-15",
                    "difficulty": "Easy",
                    "location": "Outdoor/Indoor",
                    "skills": ["Creativity", "Patience", "Precision", "Craftsmanship"],
                    "pricing": "Per Person",
                    "includes": ["Clay", "Tools", "Aprons", "Instructor"],
                    "requirements": ["Tables", "Clay", "Water", "Aprons"]
                },
                {
                    "id": "wheel-deal",
                    "title": "The Wheel Deal",
                    "subtitle": "Welcome To Spin City!",
                    "category": "creative-workshop",
                    "description": "Step up for this Wheel Pottery session and mold your masterpiece while dodging wobbles and giggles. Perfect balance, pressure, and the cleanest apron win the crown! You'll leave with a handmade treasure and a smile.",
                    "duration": "60 minutes",
                    "participants": "5-15",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Coordination", "Focus", "Technique", "Control"],
                    "pricing": "Per Person",
                    "includes": ["Pottery Wheel", "Clay", "Tools", "Instructor"],
                    "requirements": ["Pottery Wheels", "Clay", "Water", "Aprons"]
                },
                {
                    "id": "pottery-in-motion",
                    "title": "Pottery In Motion",
                    "subtitle": "Mud, Sweat and Cheers!",
                    "category": "creative-workshop",
                    "description": "Why settle for one skill when you can get your hands on both? From squishing clay in your palms to mastering the spin, this is your full-circle Combined Pottery adventure.",
                    "duration": "120 minutes",
                    "participants": "5-15",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Dexterity", "Strategy", "Skillfulness", "Adaptability"],
                    "pricing": "Per Person",
                    "includes": ["Clay", "Pottery Wheel", "Tools", "Instructor"],
                    "requirements": ["Pottery Setup", "Clay", "Water", "Aprons"]
                },
                {
                    "id": "art-attack",
                    "title": "Art Attack",
                    "subtitle": "Rough Around the Edges!",
                    "category": "creative-workshop",
                    "description": "Elevate 2D art into the third dimension as you explore the fascinating world of texture, fabrics and relief in this magnificent Texture Art workshop. Your fingers will thank you for the textural journey.",
                    "duration": "60 minutes",
                    "participants": "4-20",
                    "difficulty": "Easy",
                    "location": "Indoor",
                    "skills": ["Depth", "Innovation", "Tactility", "Composition"],
                    "pricing": "Per Person",
                    "includes": ["Textures", "Fabrics", "Canvas", "Instructor"],
                    "requirements": ["Art Supplies", "Textures", "Canvas", "Tables"]
                },
                {
                    "id": "stroke-of-genius",
                    "title": "Stroke Of Genius",
                    "subtitle": "Hue Got This!",
                    "category": "creative-workshop",
                    "description": "Whether you're channeling your inner Van Gogh or just painting for the fun of it, this Canvas Art workshop is your colorful escape from emails and meetings.",
                    "duration": "60 minutes",
                    "participants": "4-20",
                    "difficulty": "Easy",
                    "location": "Indoor",
                    "skills": ["Expression", "Perspective", "Visualization", "Creativity"],
                    "pricing": "Per Person",
                    "includes": ["Canvas", "Paints", "Brushes", "Instructor"],
                    "requirements": ["Canvas", "Paints", "Brushes", "Easels"]
                },
                {
                    "id": "connect-the-dots",
                    "title": "Connect The Dots",
                    "subtitle": "Art with a Point!",
                    "category": "creative-workshop",
                    "description": "Ever painted with just dots? In this intricate and oddly satisfying Lippan Art workshop, tiny dots create big masterpieces. Patience meets precision in a challenge that's surprisingly addictive. Let your steady hand lead the way!",
                    "duration": "60 minutes",
                    "participants": "4-20",
                    "difficulty": "Easy",
                    "location": "Indoor",
                    "skills": ["Focus", "Heritage", "Structure", "Detail"],
                    "pricing": "Per Person",
                    "includes": ["Dotting Tools", "Paints", "Canvas", "Instructor"],
                    "requirements": ["Dotting Tools", "Paints", "Canvas", "Tables"]
                },
                {
                    "id": "big-picture",
                    "title": "The Big Picture",
                    "subtitle": "Bonding Over Brushes!",
                    "category": "creative-workshop",
                    "description": "Ready for a painting party? Work on your own canvas but vibe with your team, splashing colors and ideas as you compete for the boldest creation. Can you paint a masterpiece while stealing glances at your neighbor's work? Let's find out!",
                    "duration": "120 minutes",
                    "participants": "4-20",
                    "difficulty": "Medium",
                    "location": "Indoor",
                    "skills": ["Cohesion", "Collaboration", "Synergy", "Alignment"],
                    "pricing": "Group Pricing",
                    "includes": ["Multiple Canvas", "Paints", "Brushes", "Instructor"],
                    "requirements": ["Multiple Easels", "Paints", "Brushes", "Space"]
                },
                {
                    "id": "wall-of-fame",
                    "title": "Wall Of Fame",
                    "subtitle": "From Deadlines to Doodles!",
                    "category": "creative-workshop",
                    "description": "When was the last time you were allowed to paint on walls? Brainstorm with brushes as you co-create a larger-than-life artwork. Forget boardroom meetings, this is the kind of team collaboration that leaves a real mark (on your office walls).",
                    "duration": "90 minutes",
                    "participants": "4-20",
                    "difficulty": "Medium",
                    "location": "Indoor",
                    "skills": ["Purpose", "Teamwork", "Unity", "Representation"],
                    "pricing": "Group Pricing",
                    "includes": ["Wall Paints", "Brushes", "Protective Sheets", "Instructor"],
                    "requirements": ["Wall Space", "Paints", "Brushes", "Protection"]
                },
                {
                    "id": "boogie-woogie",
                    "title": "Boogie Woogie",
                    "subtitle": "Dance Like Nobody's Watching!",
                    "category": "creative-workshop",
                    "description": "Ever turned a boardroom into a ballroom? Now's your chance. Get your team moving and grooving in this high-energy Dance workshop that boosts morale. It's a fun, rhythmic way to bond and let loose.",
                    "duration": "60 minutes",
                    "participants": "8-20",
                    "difficulty": "Easy",
                    "location": "Indoor",
                    "skills": ["Energy", "Expression", "Rhythm", "Confidence"],
                    "pricing": "Group Pricing",
                    "includes": ["Dance Instructor", "Music System", "Choreography", "Props"],
                    "requirements": ["Dance Floor", "Sound System", "Open Space", "Music"]
                },
                {
                    "id": "power-play",
                    "title": "Power Play",
                    "subtitle": "Trade your keyboard for a bat",
                    "category": "sports",
                    "description": "Ready to trade your keyboard for a bat? Turf Cricket is all about lightning-fast runs, killer catches, and team synergy. Channel your inner Kohli in this fast-paced turf battle where office rivalries meet cricket. Think you can hit it out of the park, or will you be caught short?",
                    "duration": "Half/Full Day",
                    "participants": "6-10",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Focus", "Strategy", "Team Spirit", "Agility"],
                    "pricing": "Group Pricing",
                    "includes": ["Cricket Equipment", "Turf Booking", "Umpire", "Scoreboard"],
                    "requirements": ["Cricket Turf", "Equipment", "Teams", "Umpire"]
                },
                {
                    "id": "pitch-perfect",
                    "title": "Pitch Perfect",
                    "subtitle": "Howzat for Team Building!",
                    "category": "sports",
                    "description": "The ground is bigger, the stakes are higher, and the bragging rights last till the next appraisal cycle. Get your team along for some classic Ground Cricket action. The ground is set and so is the banter!",
                    "duration": "Full Day",
                    "participants": "11-14",
                    "difficulty": "Hard",
                    "location": "Outdoor",
                    "skills": ["Endurance", "Leadership", "Teamwork", "Discipline"],
                    "pricing": "Group Pricing",
                    "includes": ["Ground Booking", "Full Cricket Kit", "Umpire", "Refreshments"],
                    "requirements": ["Cricket Ground", "Full Equipment", "Teams", "Officials"]
                },
                {
                    "id": "work-hard-play-messi",
                    "title": "Work Hard, Play Messi",
                    "subtitle": "From deadlines to goal lines!",
                    "category": "sports",
                    "description": "Prove you can actually score goals instead of just setting them. From dramatic dives to even more dramatic excuses; this is Football like HR never imagined it!",
                    "duration": "Half/Full Day",
                    "participants": "5-8",
                    "difficulty": "Hard",
                    "location": "Outdoor",
                    "skills": ["Collaboration", "Coordination", "Speed", "Awareness"],
                    "pricing": "Group Pricing",
                    "includes": ["Football", "Goal Posts", "Referee", "Field Booking"],
                    "requirements": ["Football Field", "Equipment", "Teams", "Referee"]
                },
                {
                    "id": "net-flicks-and-chill",
                    "title": "Net Flicks & Chill",
                    "subtitle": "Net Working at Its Finest!",
                    "category": "sports",
                    "description": "From keyboard clicks to shuttlecock flicks. The only acceptable place to smash things repeatedly at work. Whether you're smashing or slicing, Badminton waits for no one. Ready to serve some serious fun?",
                    "duration": "Half Day",
                    "participants": "2",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Focus", "Precision", "Reflexes", "Balance"],
                    "pricing": "Per Person",
                    "includes": ["Badminton Rackets", "Shuttlecocks", "Net", "Court Booking"],
                    "requirements": ["Badminton Court", "Rackets", "Shuttlecocks", "Net"]
                },
                {
                    "id": "pickle-punch",
                    "title": "The Pickle Punch",
                    "subtitle": "Part Tennis, Part Ping Pong, All Fun!",
                    "category": "sports",
                    "description": "Tennis was too hard, badminton too fast - welcome to the Goldilocks of office sports! Pickleball is the hybrid game you didn't know you needed.",
                    "duration": "Half Day",
                    "participants": "2",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Control", "Inclusivity", "Timing", "Adaptability"],
                    "pricing": "Per Person",
                    "includes": ["Pickleball Paddles", "Balls", "Net", "Court Booking"],
                    "requirements": ["Pickleball Court", "Paddles", "Balls", "Net"]
                },
                {
                    "id": "net-positive",
                    "title": "Net Positive",
                    "subtitle": "Raise the Stakes, Then Raise the Ball!",
                    "category": "sports",
                    "description": "One serve, one spike and one epic save. Volleyball is all about communication, timing, support and full-send dives for glory.",
                    "duration": "Half Day",
                    "participants": "6",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Cooperation", "Responsiveness", "Timing", "Alertness"],
                    "pricing": "Group Pricing",
                    "includes": ["Volleyball", "Net", "Court Booking", "Referee"],
                    "requirements": ["Volleyball Court", "Net", "Ball", "Teams"]
                },
                {
                    "id": "shoot-your-shot",
                    "title": "Shoot Your Shot",
                    "subtitle": "Slam Dunk Your Career!",
                    "category": "sports",
                    "description": "Where your vertical leap matters more than your career leap for once. Prove you can actually hit targets that aren't KPIs!",
                    "duration": "Half Day",
                    "participants": "5",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Coordination", "Focus", "Fluidity", "Agility"],
                    "pricing": "Group Pricing",
                    "includes": ["Basketball", "Court Booking", "Referee", "Scoreboard"],
                    "requirements": ["Basketball Court", "Basketballs", "Hoops", "Teams"]
                },
                {
                    "id": "dart-knight-rises",
                    "title": "The Dart Knight Rises",
                    "subtitle": "Between Dartboards and Dashboards!",
                    "category": "sports",
                    "description": "The only acceptable time to throw sharp objects at work. Precision, focus, and a steady hand can you hit the mark under pressure? One throw could make you a legend… or a laughingstock!",
                    "duration": "180 minutes",
                    "participants": "Individual",
                    "difficulty": "Easy",
                    "location": "Indoor",
                    "skills": ["Composure", "Concentration", "Patience", "Accuracy"],
                    "pricing": "Per Person",
                    "includes": ["Dart Board", "Darts", "Scoreboard", "Safety Equipment"],
                    "requirements": ["Dart Board", "Darts", "Safe Area", "Scoreboard"]
                },
                {
                    "id": "kpis-to-kms",
                    "title": "KPIs To KMs",
                    "subtitle": "Put your training to the test",
                    "category": "sports",
                    "description": "Where your only training has been running to meetings, now put it to the test! Take your team spirit to the streets in this long-distance Marathon. Whether you sprint or jog, every stride adds up. May the odds be ever in your favor (because your knees probably won't).",
                    "duration": "Half/Full Day",
                    "participants": "Variable",
                    "difficulty": "Hard",
                    "location": "Outdoor",
                    "skills": ["Motivation", "Resilience", "Stamina", "Determination"],
                    "pricing": "Per Person",
                    "includes": ["Registration", "Timing Chips", "Medals", "Refreshments"],
                    "requirements": ["Running Route", "Safety Support", "Medical Team", "Water Stations"]
                },
                {
                    "id": "ctrl-alt-defeat",
                    "title": "Ctrl + Alt + Defeat",
                    "subtitle": "The Game of Zones!",
                    "category": "sports",
                    "description": "The ultimate test of who's been 'working from home' a bit too effectively. The only workplace competition where rage-quitting is a valid strategy. From keyboards to leaderboards, E-Sports bring out the best in strategy, reflexes, and team communication.",
                    "duration": "Half Day",
                    "participants": "2-4",
                    "difficulty": "Medium",
                    "location": "Indoor",
                    "skills": ["Focus", "Reaction", "Strategy", "Collaboration"],
                    "pricing": "Group Pricing",
                    "includes": ["Gaming Setup", "Computers", "Games", "Tournament Brackets"],
                    "requirements": ["Gaming PCs", "Games", "Internet", "Tournament Setup"]
                },
                {
                    "id": "suits-to-sneakers",
                    "title": "Suits To Sneakers",
                    "subtitle": "Performance Beyond Profits!",
                    "category": "sports",
                    "description": "All the fun of Annual Sports Day, but with worse knees and better snacks! From sprints to relays, it's time to lace up and leave it all on the track. This annual tradition creates shared experiences that become touchpoints for team identity.",
                    "duration": "Half/Full Day",
                    "participants": "Variable",
                    "difficulty": "Medium",
                    "location": "Outdoor",
                    "skills": ["Engagement", "Participation", "Team Spirit", "Camaraderie"],
                    "pricing": "Group Pricing",
                    "includes": ["Sports Equipment", "Track Booking", "Medals", "Refreshments"],
                    "requirements": ["Sports Ground", "Equipment", "Officials", "Medical Support"]
                },
                {
                    "id": "winning-edge",
                    "title": "The Winning Edge",
                    "subtitle": "An evening of celebration and recognition",
                    "category": "entertainment",
                    "description": "An evening of celebration, recognition, and memorable moments. We honor the achievements, dedication, and spirit of our team. From milestones to team wins, this awards night shines a light on those who make it happen. Get ready for applause and inspiration.",
                    "duration": "180 minutes",
                    "participants": "25+",
                    "difficulty": "Maximum",
                    "location": "Indoor/Outdoor",
                    "skills": ["Leadership", "Resilience", "Breakthrough", "Vision"],
                    "pricing": "Group Pricing",
                    "includes": ["Awards", "Stage Setup", "Host", "Catering"],
                    "requirements": ["Venue", "Stage", "Awards", "Catering"]
                },
                {
                    "id": "sing-it-out",
                    "title": "Sing It Out!",
                    "subtitle": "Got a song in your heart? Let it out!",
                    "category": "entertainment",
                    "description": "This is your chance to grab the mic and share your passion (or just have a good laugh trying). Get ready for a symphony of camaraderie and maybe a few surprising solos as your team harmonizes in the most entertaining way possible!",
                    "duration": "180 minutes",
                    "participants": "10+",
                    "difficulty": "Maximum",
                    "location": "Indoor/Outdoor",
                    "skills": ["Passion", "Vibes", "Serenade", "Energy"],
                    "pricing": "Group Pricing",
                    "includes": ["Karaoke Setup", "Microphones", "Song Library", "Sound System"],
                    "requirements": ["Karaoke System", "Microphones", "Stage", "Sound System"]
                },
                {
                    "id": "mic-check",
                    "title": "Mic Check",
                    "subtitle": "Burnout? Cured. Morale? Sky-high.",
                    "category": "entertainment",
                    "description": "Our guest comic delivers laughs as your team kicks back and laughs like nobody's watching. It's the ultimate reset a break from deadlines, a burst of energy, and a reminder that the best bonding happens between punchlines.",
                    "duration": "180 minutes",
                    "participants": "10+",
                    "difficulty": "Maximum",
                    "location": "Indoor/Outdoor",
                    "skills": ["De-Stress", "Engaging", "Comedy", "Energy"],
                    "pricing": "Group Pricing",
                    "includes": ["Professional Comedian", "Stage Setup", "Sound System", "Seating"],
                    "requirements": ["Venue", "Stage", "Sound System", "Seating"]
                },
                {
                    "id": "office-unplugged",
                    "title": "Office Unplugged",
                    "subtitle": "Let the music melt the meetings away",
                    "category": "entertainment",
                    "description": "This feel good session gets your team vibing, relaxing, and connecting- no instruments, no pressure, just pure harmony and energy. A rhythm-filled break that lifts spirits, sparks creativity, and brings everyone a little closer.",
                    "duration": "180 minutes",
                    "participants": "10+",
                    "difficulty": "Maximum",
                    "location": "Indoor/Outdoor",
                    "skills": ["De-Stress", "Feel-Good", "Uplifting", "Melodious"],
                    "pricing": "Group Pricing",
                    "includes": ["Musicians", "Sound System", "Seating", "Ambient Setup"],
                    "requirements": ["Venue", "Sound System", "Seating", "Ambient Lighting"]
                },
                {
                    "id": "office-gig",
                    "title": "The Office Gig",
                    "subtitle": "Turn your 9-to-5 into a 9-to-vibe",
                    "category": "entertainment",
                    "description": "A concert-style experience right in your office. It's a high-energy break from routine with no crowd, no chaos, just live music, shared rhythm, and real connection. A fresh pulse that lifts spirits and builds camaraderie.",
                    "duration": "180 minutes",
                    "participants": "10+",
                    "difficulty": "Maximum",
                    "location": "Indoor/Outdoor",
                    "skills": ["Uplifting", "Engaging", "Joyful", "Energy"],
                    "pricing": "Group Pricing",
                    "includes": ["Live Band", "Sound System", "Stage Setup", "Lighting"],
                    "requirements": ["Venue", "Stage", "Sound System", "Lighting"]
                },
                {
                    "id": "ctrl-alt-compete",
                    "title": "Ctrl + Alt + Compete",
                    "subtitle": "Think you're the office know-it-all?",
                    "category": "entertainment",
                    "description": "Prove it—under pressure, with a buzzer in hand and your reputation on the line. This fast-paced trivia showdown gets teams thinking quick, laughing loud, and battling for bragging rights. May the sharpest mind (and loudest cheer squad) win!",
                    "duration": "120 minutes",
                    "participants": "10+",
                    "difficulty": "Adequate",
                    "location": "Indoor/Outdoor",
                    "skills": ["Team-driven", "Strategic", "Brainy", "Competitive"],
                    "pricing": "Group Pricing",
                    "includes": ["Trivia Questions", "Buzzers", "Scoreboard", "Prizes"],
                    "requirements": ["Venue", "Buzzers", "Scoreboard", "Prizes"]
                },
                {
                    "id": "movie-night",
                    "title": "Movie Night",
                    "subtitle": "Grab your crew, pick a film, and settle in",
                    "category": "entertainment",
                    "description": "Grab your crew, pick a film, and settle in for an emotional rollercoaster—popcorn included. From laughs to tears, this cinematic pause brings your team closer, one scene at a time. It's low-pressure, high-connection bonding in surround sound.",
                    "duration": "180 minutes",
                    "participants": "10+",
                    "difficulty": "Maximum",
                    "location": "Indoor/Outdoor",
                    "skills": ["Bonding-driven", "Inclusive", "Nostalgic", "Unwinding"],
                    "pricing": "Group Pricing",
                    "includes": ["Movie Selection", "Projector", "Snacks", "Seating"],
                    "requirements": ["Venue", "Projector", "Screen", "Comfortable Seating"]
                }
    ],
};