export const adminSections = [
  { path: 'dashboard', label: 'Dashboard', type: null },
  { path: 'home', label: 'Home sections', type: 'sections' },
  { path: 'about', label: 'About', type: 'sections' },
  { path: 'services', label: 'Services', type: 'services' },
  { path: 'service-categories', label: 'Service categories', type: 'service-categories' },
  { path: 'about-team', label: 'Team', type: 'team' },
  { path: 'about-process', label: 'Process', type: 'about-process' },
  { path: 'contact', label: 'Contact', type: 'contact' },
  { path: 'resources', label: 'Resources', type: 'resources' },
  { path: 'blogs', label: 'Blogs', type: 'blogs' },
  { path: 'testimonials', label: 'Testimonials', type: 'testimonials' },
  { path: 'clients', label: 'Client logos', type: 'client-logos' },
  { path: 'carousels', label: 'Carousels', type: 'carousels' },
  { path: 'navigation', label: 'Navigation', type: 'navigation' },
  { path: 'footer', label: 'Footer', type: 'footer' },
  { path: 'seo', label: 'SEO', type: 'seo' },
  { path: 'policies', label: 'Policies', type: 'policies' },
  { path: 'roi-calculator', label: 'ROI calculator', type: 'roi-calculator' },
  { path: 'culture-quiz', label: 'Culture quiz', type: 'quiz' },
  { path: 'culture-quiz-results', label: 'Quiz results', type: 'quiz-results' },
  { path: 'settings', label: 'Settings', type: 'pages' },
];

export const starterContent = {
  sections: { heading: '', description: '', image: '', ctaText: '', ctaUrl: '' },
  services: { title: '', subtitle: '', description: '', image: '', category: '', ctaText: '', ctaUrl: '' },
  'service-categories': { id: '', name: '', description: '', icon: '', gradient: '', textColor: '' },
  team: { name: '', role: '', bio: '', email: '', linkedin: '', image: '' },
  'about-process': { heading: '', description: '', steps: [] },
  contact: { heading: '', description: '', phone: '', email: '', address: '', hours: '' },
  resources: { title: '', description: '', enabled: true },
  blogs: { title: '', slug: '', category: '', excerpt: '', author: '', readTime: '', thumbnail: '', seoTitle: '', seoDescription: '' },
  testimonials: { name: '', position: '', company: '', message: '', rating: 5, profilePhoto: '' },
  'client-logos': { name: '', description: '', websiteUrl: '', logo: '' },
  carousels: { title: '', subtitle: '', description: '', image: '', mobileImage: '', ctaText: '', ctaUrl: '' },
  navigation: { label: '', url: '', visible: true, children: [] },
  footer: { label: '', value: '', url: '' },
  seo: { page: '', title: '', description: '', ogTitle: '', ogDescription: '', ogImage: '', canonicalUrl: '' },
  pages: { title: '', route: '', status: 'published' },
  policies: { title: '', lastUpdated: '', html: '' },
  'roi-calculator': { title: '', description: '', defaults: {}, benchmarks: {} },
  quiz: { title: '', intro: '', questions: [] },
  'quiz-results': { bands: [] },
};
